# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/driver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/example/nodejs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/finder/nodejs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "Python PIP"
    directory: "/finder/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "RubyGems"
    directory: "/finder/ruby"
    schedule:
      interval: "weekly"
